#!/bin/bash
# pqc-remediate.sh — PQC migration demo: baseline → remediate → rescan
set -euo pipefail
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$_SCRIPT_DIR/.."

# ── Configuration ──────────────────────────────────────────────────────────

# Resolve active profile (sets LAB_PROFILE_NAME, LAB_DOTFILE_DIR,
# VAGRANT_DOTFILE_PATH).
source "$_SCRIPT_DIR/lib/profile-helper.sh"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BASELINE_DIR="cbom-output/pqc-baseline"
RESCAN_DIR="cbom-output/pqc-rescan"
ANSIBLE_DIR="ansible"
# Per-profile inventory dir (Vagrantfile writes inventory/<profile>/pqc.ini).
INVENTORY_TEMPLATE="$ANSIBLE_DIR/inventory/$LAB_PROFILE_NAME/pqc.ini"
INVENTORY="/tmp/pqc-inventory-${LAB_PROFILE_NAME}.ini"
ANSIBLE_CFG="$ANSIBLE_DIR/ansible.cfg"
TOOLKIT_PY="cbom-toolkit/python"
OUTPUT_DIR="cbom-output"
# OpenSearch :9200 is now loopback-only on observe1 — host tooling hits the
# observe_tls nginx data port (:9244, TLS + HTTP Basic Auth) instead.
# Credentials resolve from the active profile's generated group_vars —
# no hardcoded secrets.
source "$_SCRIPT_DIR/lib/lab-secrets.sh"
OPENSEARCH_URL="${OPENSEARCH_URL:-https://$(lab_groupvar observe_ip):9244}"
export OPENSEARCH_USER="${OPENSEARCH_USER:-beats}"
export OPENSEARCH_PASS="${OPENSEARCH_PASS:-$(lab_groupvar admin_password)}"
EJBCA_TOKEN_PASSWORD="$(lab_groupvar ejbca_token_password)"
# Lab cert is from step-ca (not in the host trust store) — use -k for curl
# and --insecure for the cbom_ingest CLI.
CURL_TLS_FLAGS="${CURL_TLS_FLAGS:--k}"
CBOM_INGEST_INSECURE="${CBOM_INGEST_INSECURE:---insecure}"

SKIP_BASELINE=false
SKIP_PROVISION=false
RESET_INDEX=false

# ── Parse args ─────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-baseline)  SKIP_BASELINE=true; shift ;;
    --skip-provision) SKIP_PROVISION=true; shift ;;
    --rescan-only)    SKIP_BASELINE=true; SKIP_PROVISION=true; shift ;;
    --reset)          RESET_INDEX=true; shift ;;
    -h|--help)
      echo "Usage: $0 [options]"
      echo ""
      echo "Options:"
      echo "  --skip-baseline   Skip Phase 1 (baseline CBOM scan)"
      echo "  --skip-provision  Skip Phase 2 (VM reprovisioning + Ansible remediation)"
      echo "  --rescan-only     Skip Phases 1 and 2; run rescan + comparison only"
      echo "  --reset           Wipe OpenSearch cbom index before running. Use to"
      echo "                    clear stale docs (old classifier output, mismatched"
      echo "                    fields, etc.) so dashboards show clean post-fix data."
      echo "  -h|--help         Show this help"
      echo ""
      echo "Environment:"
      echo "  LAB_PROFILE       Active lab profile (default: core)."
      echo "                    See: bash up.sh --list-profiles"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# pqc.ini is regenerated by the Vagrantfile at parse time for the active
# profile (per-profile dotfile paths baked into vagrant_ssh_private_key_file).
# Copy to /tmp for ansible. Runs after arg parsing so --help doesn't trip it.
if [[ ! -f "$INVENTORY_TEMPLATE" ]]; then
  echo "ERROR: $INVENTORY_TEMPLATE missing — run \`bash scripts/render-inventory.sh\` or any vagrant command first." >&2
  exit 1
fi
cp "$INVENTORY_TEMPLATE" "$INVENTORY"

# ── Optional: wipe cbom index before run ───────────────────────────────────

if [[ "$RESET_INDEX" == true ]]; then
  banner_text="═══ Resetting OpenSearch cbom index ═══"
  echo -e "\n\033[1m${banner_text}\033[0m\n"
  # Delete + recreate with the same mapping the opensearch_stack role uses.
  # If observe1 isn't reachable, warn and continue — re-ingestion below will
  # still create the index lazily (without explicit mapping).
  delete_status=$(curl -s $CURL_TLS_FLAGS -u "$OPENSEARCH_USER:$OPENSEARCH_PASS" \
    -o /dev/null -w '%{http_code}' -X DELETE "$OPENSEARCH_URL/cbom" 2>/dev/null || echo 000)
  if [[ "$delete_status" =~ ^(200|404)$ ]]; then
    echo -e "\033[32m[pqc]\033[0m cbom index deleted (status $delete_status)"
  else
    echo -e "\033[33m[pqc]\033[0m cbom index delete returned $delete_status — proceeding anyway"
  fi
  # Recreate with the keyword/date mappings (must match opensearch_stack role)
  curl -s $CURL_TLS_FLAGS -u "$OPENSEARCH_USER:$OPENSEARCH_PASS" \
    -o /dev/null -X PUT "$OPENSEARCH_URL/cbom" \
    -H 'Content-Type: application/json' \
    -d '{"mappings":{"properties":{
      "@timestamp":{"type":"date"},"message":{"type":"text"},
      "cbom_scanner":{"type":"keyword"},"cbom_scan_time":{"type":"date"},
      "cbom_asset_type":{"type":"keyword"},"cbom_vm":{"type":"keyword"},
      "cbom_name":{"type":"keyword"},"cbom_location":{"type":"keyword"},
      "cbom_bom_ref":{"type":"keyword"},"cbom_event_type":{"type":"keyword"},
      "cbom_pqc_status":{"type":"keyword"},"cbom_algorithm":{"type":"keyword"},
      "cbom_primitive":{"type":"keyword"},"cbom_subject":{"type":"keyword"},
      "cbom_issuer":{"type":"keyword"},"cbom_not_before":{"type":"date"},
      "cbom_not_after":{"type":"date"},"cbom_sig_algorithm":{"type":"keyword"},
      "cbom_days_to_expiry":{"type":"integer"},"cbom_is_root":{"type":"boolean"},
      "cbom_key_type":{"type":"keyword"},"cbom_key_size":{"type":"integer"},
      "cbom_pqc_only":{"type":"boolean"}
    }}}' 2>/dev/null
  echo -e "\033[32m[pqc]\033[0m cbom index recreated with full mapping"
fi

# ── Helpers ────────────────────────────────────────────────────────────────

log()    { echo -e "\033[36m[pqc]\033[0m $*"; }
ok()     { echo -e "\033[32m[pqc]\033[0m $*"; }
warn()   { echo -e "\033[33m[pqc]\033[0m $*"; }
err()    { echo -e "\033[31m[pqc]\033[0m $*" >&2; }
banner() { echo -e "\n\033[1m$*\033[0m\n"; }

run_ansible() {
  local playbook="$1"; shift
  ANSIBLE_CONFIG="$ANSIBLE_CFG" ansible-playbook -i "$INVENTORY" "$ANSIBLE_DIR/playbooks/$playbook" "$@"
}

# ── Phase 1: Baseline Scan ─────────────────────────────────────────────────

if [[ "$SKIP_BASELINE" == false ]]; then
  banner "═══ Phase 1: Baseline Scan ═══"

  mkdir -p "$BASELINE_DIR"

  log "Running nmap-network baseline scan..."
  bash scripts/cbom-pipeline.sh --scanner nmap-network --no-export --no-ingest 2>&1 | sed 's/^/  /'

  # Copy latest nmap deduped result to baseline dir
  LATEST_NMAP=$(ls -t "$OUTPUT_DIR"/cbom-nmap-network-${LAB_PROFILE_NAME}-*-deduped.json 2>/dev/null | head -1 || true)
  if [[ -n "$LATEST_NMAP" ]]; then
    cp "$LATEST_NMAP" "$BASELINE_DIR/baseline-nmap-$TIMESTAMP.json"
    ok "Baseline saved: $BASELINE_DIR/baseline-nmap-$TIMESTAMP.json"
  else
    warn "No nmap deduped output found — baseline not saved"
  fi

  # Score the baseline
  log "PQC baseline scorecard..."
  if [[ -n "$LATEST_NMAP" ]]; then
    python3 "$TOOLKIT_PY/cbom_score.py" "$LATEST_NMAP" 2>&1 | sed 's/^/  /'
  fi
else
  log "Skipping Phase 1 (--skip-baseline)"
fi

# ── Phase 2: Remediation ───────────────────────────────────────────────────

if [[ "$SKIP_PROVISION" == false ]]; then
  banner "═══ Phase 2: Remediation ═══"

  # Extract organization from config.rb (LAB_NETBIOS default)
  LAB_ORG=$(grep -oP "(?<=LAB_NETBIOS\s{8}= ENV\['LAB_NETBIOS'\]\s\|\|\s\")([^\"]+)" vagrant/config.rb 2>/dev/null \
            || grep -oP '(?<=LAB_NETBIOS\s{8}= ENV\[.LAB_NETBIOS.\] \|\| ")[^"]+' config.rb 2>/dev/null \
            || echo "YOURLAB")

  # Simpler grep for the default value: LAB_NETBIOS ... || "YOURLAB"
  if [[ "$LAB_ORG" == "YOURLAB" ]]; then
    LAB_ORG=$(grep 'LAB_NETBIOS' config.rb 2>/dev/null | grep '||' | grep -oP '"\K[^"]+(?=")' | tail -1 || echo "YOURLAB")
  fi

  log "Using organization: $LAB_ORG"

  # 2a: Reprovision EJBCA (upgrade to 9.3)
  log "2a: Reprovisioning ejbca1 (EJBCA CE 9.3)..."
  vagrant provision ejbca1 2>&1 | sed 's/^/  /'
  ok "ejbca1 reprovisioned"

  # 2b: PQC CA creation on EJBCA via Ansible
  log "2b: Creating PQC CAs on EJBCA (ML-DSA-65 + chimera)..."
  run_ansible pqc-ejbca.yml \
    -e "ejbca_token_password=$EJBCA_TOKEN_PASSWORD" \
    -e "ejbca_organization=$LAB_ORG" \
    2>&1 | sed 's/^/  /'
  ok "EJBCA PQC CAs configured"

  # 2c: Reprovision step-ca (upgrade + PQC TLS)
  log "2c: Reprovisioning stepca1 (step-ca upgrade + PQC TLS)..."
  vagrant provision stepca1 2>&1 | sed 's/^/  /'
  ok "stepca1 reprovisioned"

  # 2d: AD CS PQC audit
  log "2d: Running AD CS PQC audit on CA1..."
  run_ansible pqc-adcs-audit.yml 2>&1 | sed 's/^/  /'
  ok "AD CS PQC audit complete"

  # 2e: PQC enrollment across platforms
  log "2e: Running PQC enrollment playbook..."
  run_ansible pqc-enroll.yml \
    -e "ejbca_token_password=$EJBCA_TOKEN_PASSWORD" \
    -e "lab_domain=yourlab.local" \
    -e "ejbca_export_dir=/opt/ejbca/data/export" \
    2>&1 | sed 's/^/  /'
  ok "PQC enrollment complete"

  # 2f: Chimera profile + cert + nginx demo (needs two-tier AD CS + IIS host)
  # Profiles that include both dc1 + web1: pqc-full, ad-cs-two-tier, full.
  # Detect by checking the rendered pqc.ini for the
  # [iis] + [domain_controllers] groups so this stays in sync with whatever
  # profile selection logic vagrant uses, without duplicating the list.
  if grep -q '^\[iis\]' "$INVENTORY_TEMPLATE" 2>/dev/null && \
     grep -q '^\[domain_controllers\]' "$INVENTORY_TEMPLATE" 2>/dev/null; then
    log "2f: Running chimera playbook (admin bootstrap + profile + enrollment + nginx demo)..."
    run_ansible pqc-chimera.yml \
      -e "ejbca_token_password=$EJBCA_TOKEN_PASSWORD" \
      -e "lab_domain=yourlab.local" \
      2>&1 | sed 's/^/  /'
    ok "Chimera demo complete"
  else
    log "2f: skipping chimera (profile lacks iis + domain_controllers groups)"
  fi
else
  log "Skipping Phase 2 (--skip-provision)"
fi

# ── Phase 3: Rescan ────────────────────────────────────────────────────────

banner "═══ Phase 3: Rescan ═══"

mkdir -p "$RESCAN_DIR"

# Nmap rescan
log "Running nmap-network rescan..."
bash scripts/cbom-pipeline.sh --scanner nmap-network --no-export --no-ingest 2>&1 | sed 's/^/  /'

RESCAN_NMAP=$(ls -t "$OUTPUT_DIR"/cbom-nmap-network-${LAB_PROFILE_NAME}-*-deduped.json 2>/dev/null | head -1 || true)
if [[ -n "$RESCAN_NMAP" ]]; then
  cp "$RESCAN_NMAP" "$RESCAN_DIR/rescan-nmap-$TIMESTAMP.json"
  ok "nmap rescan saved: $RESCAN_DIR/rescan-nmap-$TIMESTAMP.json"
else
  warn "No nmap rescan output found"
fi

# EJBCA API rescan
log "Running ejbca-api rescan..."
bash scripts/cbom-pipeline.sh --scanner ejbca-api --no-export --no-ingest 2>&1 | sed 's/^/  /'

RESCAN_EJBCA=$(ls -t "$OUTPUT_DIR"/cbom-ejbca-api-${LAB_PROFILE_NAME}-*-deduped.json 2>/dev/null | head -1 || true)
if [[ -n "$RESCAN_EJBCA" ]]; then
  cp "$RESCAN_EJBCA" "$RESCAN_DIR/rescan-ejbca-$TIMESTAMP.json"
  ok "ejbca-api rescan saved: $RESCAN_DIR/rescan-ejbca-$TIMESTAMP.json"
else
  warn "No ejbca-api rescan output found"
fi

# PQC handshake probe rescan (sees pure-PQC endpoints nmap can't handshake with)
log "Running pqc-handshake rescan..."
bash scripts/cbom-pipeline.sh --scanner pqc-handshake --no-export --no-ingest 2>&1 | sed 's/^/  /'

RESCAN_PQCHS=$(ls -t "$OUTPUT_DIR"/cbom-pqc-handshake-${LAB_PROFILE_NAME}-*-deduped.json 2>/dev/null | head -1 || true)
if [[ -n "$RESCAN_PQCHS" ]]; then
  cp "$RESCAN_PQCHS" "$RESCAN_DIR/rescan-pqc-handshake-$TIMESTAMP.json"
  ok "pqc-handshake rescan saved: $RESCAN_DIR/rescan-pqc-handshake-$TIMESTAMP.json"
else
  warn "No pqc-handshake rescan output found"
fi

# PQC SSH probe rescan (mlkem768x25519-sha256 KEX negotiation across linux_pqc_targets)
log "Running pqc-ssh rescan..."
bash scripts/cbom-pipeline.sh --scanner pqc-ssh --no-export --no-ingest 2>&1 | sed 's/^/  /'

RESCAN_PQCSSH=$(ls -t "$OUTPUT_DIR"/cbom-pqc-ssh-${LAB_PROFILE_NAME}-*-deduped.json 2>/dev/null | head -1 || true)
if [[ -n "$RESCAN_PQCSSH" ]]; then
  cp "$RESCAN_PQCSSH" "$RESCAN_DIR/rescan-pqc-ssh-$TIMESTAMP.json"
  ok "pqc-ssh rescan saved: $RESCAN_DIR/rescan-pqc-ssh-$TIMESTAMP.json"
else
  warn "No pqc-ssh rescan output found"
fi

# PQC OpenPGP probe rescan (Kyber subkeys discovered via gpg --list-keys on each target)
log "Running pqc-openpgp rescan..."
bash scripts/cbom-pipeline.sh --scanner pqc-openpgp --no-export --no-ingest 2>&1 | sed 's/^/  /'

RESCAN_PQCPGP=$(ls -t "$OUTPUT_DIR"/cbom-pqc-openpgp-${LAB_PROFILE_NAME}-*-deduped.json 2>/dev/null | head -1 || true)
if [[ -n "$RESCAN_PQCPGP" ]]; then
  cp "$RESCAN_PQCPGP" "$RESCAN_DIR/rescan-pqc-openpgp-$TIMESTAMP.json"
  ok "pqc-openpgp rescan saved: $RESCAN_DIR/rescan-pqc-openpgp-$TIMESTAMP.json"
else
  warn "No pqc-openpgp rescan output found"
fi

# ── Phase 4: Comparison ────────────────────────────────────────────────────

banner "═══ Phase 4: Comparison ═══"

# Diff baseline vs nmap rescan
BASELINE_NMAP=$(ls -t "$BASELINE_DIR"/baseline-nmap-*.json 2>/dev/null | head -1 || true)
if [[ -n "$BASELINE_NMAP" && -n "$RESCAN_NMAP" ]]; then
  log "Diffing baseline vs rescan (nmap)..."
  python3 "$TOOLKIT_PY/cbom_diff.py" "$BASELINE_NMAP" "$RESCAN_DIR/rescan-nmap-$TIMESTAMP.json" 2>&1 | sed 's/^/  /' || true
else
  warn "Skipping diff — baseline or rescan nmap result not available"
fi

# Score nmap rescan
if [[ -n "$RESCAN_NMAP" ]]; then
  log "PQC rescan scorecard (nmap)..."
  python3 "$TOOLKIT_PY/cbom_score.py" "$RESCAN_DIR/rescan-nmap-$TIMESTAMP.json" 2>&1 | sed 's/^/  /'
fi

# Score ejbca-api rescan
if [[ -n "$RESCAN_EJBCA" ]]; then
  log "PQC rescan scorecard (ejbca-api)..."
  python3 "$TOOLKIT_PY/cbom_score.py" "$RESCAN_DIR/rescan-ejbca-$TIMESTAMP.json" 2>&1 | sed 's/^/  /'
fi

# Score pqc-handshake rescan
if [[ -n "$RESCAN_PQCHS" ]]; then
  log "PQC rescan scorecard (pqc-handshake — sees pure-PQC endpoints)..."
  python3 "$TOOLKIT_PY/cbom_score.py" "$RESCAN_DIR/rescan-pqc-handshake-$TIMESTAMP.json" 2>&1 | sed 's/^/  /'
fi

# Score pqc-ssh rescan
if [[ -n "$RESCAN_PQCSSH" ]]; then
  log "PQC rescan scorecard (pqc-ssh — sees mlkem768x25519-sha256 KEX)..."
  python3 "$TOOLKIT_PY/cbom_score.py" "$RESCAN_DIR/rescan-pqc-ssh-$TIMESTAMP.json" 2>&1 | sed 's/^/  /'
fi

# Score pqc-openpgp rescan
if [[ -n "$RESCAN_PQCPGP" ]]; then
  log "PQC rescan scorecard (pqc-openpgp — sees Kyber subkeys)..."
  python3 "$TOOLKIT_PY/cbom_score.py" "$RESCAN_DIR/rescan-pqc-openpgp-$TIMESTAMP.json" 2>&1 | sed 's/^/  /'
fi

# Ingest nmap rescan to OpenSearch
if [[ -n "$RESCAN_NMAP" ]]; then
  log "Ingesting nmap rescan to OpenSearch (event-type: pqc-rescan)..."
  python3 "$TOOLKIT_PY/cbom_ingest.py" "$RESCAN_DIR/rescan-nmap-$TIMESTAMP.json" \
    --scanner nmap-network \
    --opensearch-url "$OPENSEARCH_URL" $CBOM_INGEST_INSECURE \
    --event-type pqc-rescan 2>&1 | sed 's/^/  /' || warn "OpenSearch ingest failed — is OBSERVE1 running?"
fi

# Ingest ejbca-api rescan to OpenSearch
if [[ -n "$RESCAN_EJBCA" ]]; then
  log "Ingesting ejbca-api rescan to OpenSearch (event-type: pqc-rescan)..."
  python3 "$TOOLKIT_PY/cbom_ingest.py" "$RESCAN_DIR/rescan-ejbca-$TIMESTAMP.json" \
    --scanner ejbca-api \
    --opensearch-url "$OPENSEARCH_URL" $CBOM_INGEST_INSECURE \
    --event-type pqc-rescan 2>&1 | sed 's/^/  /' || warn "OpenSearch ingest failed — is OBSERVE1 running?"
fi

# Ingest pqc-handshake rescan to OpenSearch
if [[ -n "$RESCAN_PQCHS" ]]; then
  log "Ingesting pqc-handshake rescan to OpenSearch (event-type: pqc-rescan)..."
  python3 "$TOOLKIT_PY/cbom_ingest.py" "$RESCAN_DIR/rescan-pqc-handshake-$TIMESTAMP.json" \
    --scanner pqc-handshake \
    --opensearch-url "$OPENSEARCH_URL" $CBOM_INGEST_INSECURE \
    --event-type pqc-rescan 2>&1 | sed 's/^/  /' || warn "OpenSearch ingest failed — is OBSERVE1 running?"
fi

# Ingest pqc-ssh rescan to OpenSearch
if [[ -n "$RESCAN_PQCSSH" ]]; then
  log "Ingesting pqc-ssh rescan to OpenSearch (event-type: pqc-rescan)..."
  python3 "$TOOLKIT_PY/cbom_ingest.py" "$RESCAN_DIR/rescan-pqc-ssh-$TIMESTAMP.json" \
    --scanner pqc-ssh \
    --opensearch-url "$OPENSEARCH_URL" $CBOM_INGEST_INSECURE \
    --event-type pqc-rescan 2>&1 | sed 's/^/  /' || warn "OpenSearch ingest failed — is OBSERVE1 running?"
fi

# Ingest pqc-openpgp rescan to OpenSearch
if [[ -n "$RESCAN_PQCPGP" ]]; then
  log "Ingesting pqc-openpgp rescan to OpenSearch (event-type: pqc-rescan)..."
  python3 "$TOOLKIT_PY/cbom_ingest.py" "$RESCAN_DIR/rescan-pqc-openpgp-$TIMESTAMP.json" \
    --scanner pqc-openpgp \
    --opensearch-url "$OPENSEARCH_URL" $CBOM_INGEST_INSECURE \
    --event-type pqc-rescan 2>&1 | sed 's/^/  /' || warn "OpenSearch ingest failed — is OBSERVE1 running?"
fi

# ── Final Summary ──────────────────────────────────────────────────────────

banner "═══ PQC Remediation Loop Complete ═══"
ok "Timestamp:        $TIMESTAMP"
ok "Profile:          $LAB_PROFILE_NAME"
ok ""
ok "Outputs:"
[[ -n "$BASELINE_NMAP" ]]  && ok "  Baseline (nmap):  $BASELINE_DIR/baseline-nmap-$TIMESTAMP.json"     || true
[[ -n "$RESCAN_NMAP" ]]    && ok "  Rescan (nmap):    $RESCAN_DIR/rescan-nmap-$TIMESTAMP.json"         || true
[[ -n "$RESCAN_EJBCA" ]]   && ok "  Rescan (ejbca):   $RESCAN_DIR/rescan-ejbca-$TIMESTAMP.json"        || true
[[ -n "$RESCAN_PQCHS" ]]   && ok "  Rescan (pqc-hs):  $RESCAN_DIR/rescan-pqc-handshake-$TIMESTAMP.json" || true
ok ""
ok "Platform status:"
[[ "$SKIP_PROVISION" == false ]] && ok "  EJBCA 9.3:        provisioned + PQC CAs created" || ok "  EJBCA:            (skipped)"
[[ "$SKIP_PROVISION" == false ]] && ok "  step-ca:          provisioned + PQC TLS enabled" || ok "  step-ca:          (skipped)"
[[ "$SKIP_PROVISION" == false ]] && ok "  AD CS:            audit complete"                 || ok "  AD CS:            (skipped)"
ok ""
ok "Dashboards: http://$(lab_groupvar observe_ip):5601/app/dashboards"
