import os, sys, tempfile, unittest
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import creds  # noqa: E402

_INV = """# Generated by Vagrantfile — do not edit manually
dc1 ansible_connection=winrm ansible_user=vagrant ansible_password=vagrant ansible_port=5985 ansible_winrm_transport=basic ansible_host=192.168.59.10
ejbca1 ansible_connection=ssh ansible_user=vagrant ansible_python_interpreter=/usr/bin/python3 ansible_host=192.168.59.50
"""


def _mkrepo(root, profile="pqc-full", inventory=_INV, with_key=True):
    inv_dir = os.path.join(root, "ansible", "inventory", profile)
    os.makedirs(inv_dir)
    with open(os.path.join(inv_dir, "static.ini"), "w") as fh:
        fh.write(inventory)
    if with_key:
        kd = os.path.join(root, f".vagrant-{profile}", "machines", "ejbca1", "virtualbox")
        os.makedirs(kd)
        with open(os.path.join(kd, "private_key"), "w") as fh:
            fh.write("FAKE KEY\n")


class TestCreds(unittest.TestCase):
    def test_winrm_descriptor_from_inventory(self):
        with tempfile.TemporaryDirectory() as root:
            _mkrepo(root)
            d = creds.resolve("dc1", "pqc-full", root)
            self.assertTrue(d["available"])
            self.assertEqual(d["transport"], "winrm")
            self.assertEqual(d["ip"], "192.168.59.10")
            self.assertEqual(d["port"], 5985)
            self.assertEqual(d["user"], "vagrant")
            self.assertEqual(d["password"], "vagrant")
            self.assertEqual(d["ip_source"], "inventory")

    def test_ssh_descriptor_with_dotfile_key(self):
        with tempfile.TemporaryDirectory() as root:
            _mkrepo(root)
            d = creds.resolve("ejbca1", "pqc-full", root)
            self.assertTrue(d["available"])
            self.assertEqual(d["transport"], "ssh")
            self.assertEqual(d["ip"], "192.168.59.50")
            self.assertEqual(d["port"], 22)
            self.assertTrue(d["key"].endswith(
                ".vagrant-pqc-full/machines/ejbca1/virtualbox/private_key"))

    def test_ssh_without_key_is_unavailable(self):
        with tempfile.TemporaryDirectory() as root:
            _mkrepo(root, with_key=False)
            d = creds.resolve("ejbca1", "pqc-full", root)
            self.assertFalse(d["available"])
            self.assertIn("key", d["reason"])

    def test_unknown_vm_is_unavailable(self):
        with tempfile.TemporaryDirectory() as root:
            _mkrepo(root)
            d = creds.resolve("nonesuch9", "pqc-full", root)
            self.assertFalse(d["available"])

    def test_missing_inventory_is_unavailable_never_raises(self):
        with tempfile.TemporaryDirectory() as root:
            d = creds.resolve("dc1", "pqc-full", root)
            self.assertFalse(d["available"])
            self.assertIn("inventory", d["reason"])

    def test_garbage_port_is_unavailable_never_raises(self):
        with tempfile.TemporaryDirectory() as root:
            inv = ("dc1 ansible_connection=winrm ansible_user=vagrant "
                   "ansible_password=vagrant ansible_port=garbage "
                   "ansible_host=192.168.59.10\n")
            _mkrepo(root, inventory=inv)
            d = creds.resolve("dc1", "pqc-full", root)
            self.assertFalse(d["available"])
            self.assertIn("port", d["reason"])

    def test_comment_and_blank_lines_skipped(self):
        with tempfile.TemporaryDirectory() as root:
            _mkrepo(root)
            inv = creds.load_inventory(os.path.join(
                root, "ansible", "inventory", "pqc-full", "static.ini"))
            self.assertEqual(set(inv), {"dc1", "ejbca1"})


if __name__ == "__main__":
    unittest.main()
